title: Useful Scripts Documentation
description: A blog for documenting how and when to use the scripts in this repository.
baseurl: "/useful_scripts" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: ojisanchamchi # Replace with your GitHub username

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
show_excerpts: true
future: true
